name: exercise5_hero_animations
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/flippers-alpha.png